
export const AppsData = [
    {
      title: "Flickering",
      subtitle: "MERN GraphJS Apollo",
      description:"A tracker for your emotions / mood.",
      image: "./assets/projects/flickering_notesPage.jpg",
      link: "https://flickering.herokuapp.com",
      github: "https://github.com/Mark33Mark/flickering",
    },
    {
      title: "Quot3d",
      subtitle: "Express SQL Heroku",
      description:"A quote feed of over 1600 quotes.",
      image: "./assets/projects/screengrab_quoted1.jpg",
      link: "https://quote.watsonised.com",
      github: "https://github.com/Mark33Mark/quoted",
    },
    {
      title: "J.A.T.E.",
      subtitle: "PWA IndexedDB Heroku ",
      description:"An installable PWA for script editing.",
      image: "./assets/projects/JATE_screengrab.jpg",
      link: "https://jate-editor.herokuapp.com",
      github: "https://github.com/Mark33Mark/PWA_text_editor",
    },
    {
      title: "ToDo",
      subtitle: "React LocalStorage gh-pages",
      description:"Simple React app for managing your tasks.",
      image: "./assets/projects/todo_screengrab.jpg",
      link: "https://todo.watsonised.com",
      github: "https://github.com/Mark33Mark/react-todo-app",
    },
    {
      title: "Tech-Yes",
      subtitle: "mySQL Sequelize BCrypt Heroku",
      description:"A blog site with user authentication.",
      image: "./assets/projects/tech_yes_screengrab.jpg",
      link: "https://tech-yes.herokuapp.com/",
      github: "https://github.com/Mark33Mark/tech-yes",
    },
    {
      title: "Weather Dash",
      subtitle: "Open-Weather API LocalStorage",
      description:"Remembers multiple locations.",
      image: "./assets/projects/weather_dash.jpg",
      link: "https://sun.watsonised.com",
      github: "https://github.com/Mark33Mark/weather-dashboard",
    },
    {
      title: "Lettuce-Eat",
      subtitle: "API CSS JavaScript",
      description:"A recipe generating application.",
      image: "./assets/projects/lettuce_eat.jpg",
      link: "https://eat.watsonised.com",
      github: "https://github.com/Mark33Mark/recipe-generator",
    },
    {
      title: "Quiz",
      subtitle: "JavaScript CSS",
      description:"A fun template for hosting online quizzes.",
      image: "./assets/projects/code_quiz.jpg",
      link: "https://quiz.watsonised.com",
      github: "https://github.com/Mark33Mark/code-quiz_webAPI",
    },
    {
      title: "Scheduler",
      subtitle: "JavaScript CSS LocalStorage",
      description:"Simple but effective daily scheduler.",
      image: "./assets/projects/workday_scheduler.jpg",
      link: "https://task.watsonised.com",
      github: "https://github.com/Mark33Mark/workday-scheduler",
    },
    {
      title: "Flick3d",
      subtitle: "MySQL Heroku GSAP Sequelize",
      description:"Find when a movie release date for next 12 months.",
      image: "./assets/projects/flicked_landing.jpg",
      link: "https://flick3d.herokuapp.com",
      github: "https://github.com/Mark33Mark/movie-scheduler",
    },
  ];
  
  // Here for a future update when I actually get some references for work I've done.
  export const Testimonials = [
    {
      quote:"",
      image: "",
      name: "",
      company: "",
    },
    {
      quote:"",
      image: "",
      name: "",
      company: "",
    },
  ];
  
  export const Skills = [
    "API's",
    "AWS",
    "C",
    "CSS",
    "DynamoDB",
    "Express",
    "Git",
    "GraphJS",
    "GraphQL",
    "Heroku",
    "HTML",
    "JavaScript",
    "MongoDB",
    "Mongoose",
    "Netlify",
    "Node",
    "NoSQL",
    "Python",
    "React",
    "S3 and EC2",
    "Sequelize",
    "SQL",
  ];
  